
# # -*- coding: utf-8 -*-
# """Untitled0.ipynb

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1ERJSgDln6cwWO9zWdePp8bfCrBdySdeY
# """

from ast import For
import json
import requests
import pandas as pd
import time

read = pd.read_excel(r'C:\Users\fnafisa\WORKSPACE\CRs\input\CRs FAHAD.xlsx')
# print(read['CR'])

companyCrlist = []
Type = []
issueHijriDate = []
expiryHijriDate = []
City = []
name = []
legalType = []
Status = []
statusReason = []
activities = []

ERRORcompanyCrlist = []
# ERRORcrType = []
# ERRORissueHijriDate = []
# ERRORexpiryHijriDate = []
# ERRORCity = []
# ERRORname = []
# ERRORlegalType = []
# ERRORstatus = []
# ERRORstatusReason = []
# ERRORactivities = []

loopcounter = 10
counter = 0
fileNumber = 1
remainingCR = 0

while(read.size >= 1):
    print(read.size)
    for i  in read['CR']:
        response = ''
        

        while True:
            
            try:
                response = requests.post(f"http://37.224.45.149/MCIMIDDLEWARE/public/api/mc/crinfo?cr_number={i}",
                            headers={"accept":"application/json"})
                break
            except Exception: # Try to catch something more specific
                pass

        print(i)
        status = response.status_code
        print(status)
        
        info = json.loads(response.text)
        #   print(type(info))
        #   print(info)

        if(status == 256):
            
            for j in info['ISICActivitiesList']['ISICActivity']:
                try:
                    x = str(j['ISICName'])
                except:
                    x = str(info['ISICActivitiesList']['ISICActivity'])

                companyCrlist.append(i)
                Type.append(info['CRType'])
                issueHijriDate.append(info['CRIssueHijriDate'])
                expiryHijriDate.append(info['CRExpiryHijriDate'])
                City.append(info['CRCityAR'])
                name.append(info['CRNameAR'])
                legalType.append(info['CRLegalTypeAR'])
                Status.append(info['CRStatus'])
                statusReason.append(info['CRStatusReasonAr'])
                activities.append(x)
                
        else:
            ERRORcompanyCrlist.append(i)

        response.close
        


    df = pd.DataFrame({'CR': ERRORcompanyCrlist})
    df.to_excel('ERROR result' + str(fileNumber) + '.xlsx')

    read = pd.read_excel('ERROR result'+ str(fileNumber) +'.xlsx')
    ERRORcompanyCrlist = []
    fileNumber = fileNumber + 1





df = pd.DataFrame({'Company CR': companyCrlist,
                    'CRType': Type,
                    'CRIssueHijriDate': issueHijriDate,
                    'CRExpiryHijriDate': expiryHijriDate,
                    'CRCityAR': City,
                    'CRNameAR': name,
                    'LegalTypeAR': legalType,
                    'CRStatus': Status,
                    'CRStatusReasonAr': statusReason,
                    'activities': activities,
        })
df.to_excel(r'C:\Users\fnafisa\WORKSPACE\CRs\output\result.xlsx')